name: ISSUE

on:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn compile

      - name: Run with Maven
        run: mvn exec:java -Dexec.mainClass="com.itlgl.jekyll.NoteGenerate" -Dexec.args="arg0 arg1 arg2"
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Commit files
        if: github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'labeled' || github.event.action == 'unlabeled'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./content
          git commit -a -m "update issue ${{ github.event.issue.number }} content"

      - name: Commit files
        if: github.event.action == 'deleted'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git rm ./content/posts/${{ github.event.issue.number }}.md
          git commit -a -m "update content/posts/${{ github.event.issue.number }}.md"

      - name: Push changes
        run: git push
